### ISSUE TITLE
fav button - initial implementation

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#1]

**Comment by jturtler** [comment]
test

**Comment by gregrowles** [comment]
based on James' schema changes

**Comment by gregrowles** [comment]
![fav.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46ee958c61cec1b99de6b546a749b2ce6b1324237f5df27c2884ba78e8132a515f094ff8130c584cf5eb9539e4e76224d50152a7842f4d7ed43c16a6b9871bbc08b9268c4982b6bc8b5e8d.png)

**Comment by gregrowles** [comment]
Add 'Sync' ALL button?

**Comment by BRaimbault** [comment]
*On 'Sync ALL' button:*
 Can we have this discussion in another card to see what would be the best option (does it needs to be in the fav list or somewhere else?)

*On the fav-list:*
We probably need to differentiate targetOnline and targetOffline:
![fav_list.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46ee958c1c8e8aba9babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901eb80bbb258f4b84b0b48a45c2ed3e27f5c6.jpg)

**Comment by BRaimbault** [comment]
Fav button target:
- an area + a block

**Comment by gregrowles** [comment]
Done, and done; display sequence issue also resolved (for testing with next upload); 
Outstanding: support for online+offline mode #30
