### ISSUE TITLE
List clean up

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#12]
*Version tested: 1.0.20*

- It looks like the active bar is not necessary at the moment, I believe in the future it will be used to include options to filter the content of the list.
- We dont need the lock icon and the accompanying text. I think the arrows icon conveys and colors conveys properly the idea of not synced / synced status of the record.
- This text should be replaced by some specific information to identify the record (eg. voucher code / first name of client / service received), in the future this will be configurable.
- We should adopt a more compact format for the date-time (eg. 18-12-06 16:07)

![Screenshot_2018-12-06-16-00-20.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417753e7952ee7a26c8b378f2102b43434d0eee1e020a17b8eb8339a3e53c76835d0ce580645f73c73c11acee834bed55bd28825d99a4fedb1294b7607caddecd5d340c041183fe5831a4984bc05cf14fe64552b65e.jpg)

**Comment by gregrowles** [comment]
We can discuss over skype, have implemented date+time changes plus reduced icons + status text
![untitles.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46fd9a8e2a968fac9cabf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901eb80bbb258f4b80b4b48948c9e13e23f5c6.png)
