### ISSUE TITLE
Forms headers clean up

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#16]
![capture_header.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46eb958a379791acb0e1ba42a058e2d665043761260ea62864c7b96aea412b57565e49a410515f43fdf8892bf0b76822de5b03e4c3714d36976345f3e5db55ea43a82a994e8cbcbd8f48c4e93a25e78988473f1f1755.jpg)

(1) Make name match activity selected on the fav button
(2) Replace icon with menu button
(3) Replace current online/offline icon with the one provided by the designer

Remove other elements.

**Comment by gregrowles** [comment]
Can we pls revise (1) ? App title is now replaced by name of current user;
(2) done
(3) have improvised network online/offline SVG icons (until designer comes back to us)

**Comment by BRaimbault** [comment]
(1) Ok
(2) Ok 
(3) #30
