### ISSUE TITLE
About Screen

### ISSUE THREAD

**Issue by gregrowles** [psi-mis/connectPWA-pm#2]
display necessary 'about' information in separate screen

**Comment by gregrowles** [comment]
improve styling

**Comment by BRaimbault** [comment]
We will have to review later for smaller screens:
![Screenshot_4.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf01fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3b88e48c5e93820e28c8d4f2c53.jpg)

It looks good for now we will open a new card later.
