### ISSUE TITLE
when data server is down act as offline

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#20]
Network available but data server not

Use "available" endpoint

**Comment by BRaimbault** [comment]
Decide between 2 or 3 icons.

**Comment by gregrowles** [comment]
Test initiated but this may be complex as serverUp() test runs for up to 3 seconds; networkOnline() test runs every 500 milliseconds; need an innovative approach to marry these two processes as networkOnline must preempt serverUp() method

**Comment by gregrowles** [comment]
dataServer availability test being done every 30sec; network conditions check runs every 0.5sec; when network is available there might be a short delay between seeing the offline+unavailable icon:
![dataServerOffline.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46ec958e22b186bb99ecad6ca25bfc9d2743653f6b14b1247a80e03cfd1839540c5f48a5405f5715f5f98e2aa7b63c268b0859b9d6655666da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3825e08f8a4c3e16021a8ced10.png)
