### ISSUE TITLE
search list result styling

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#21]

**Comment by BRaimbault** [comment]
Bruno

**Comment by gregrowles** [comment]
should we remove this? associated with card #3 and #19

**Comment by BRaimbault** [comment]
[CwS - Search results.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46cb83a963cfc39a8ae8ad40ac1de2913a532b673a46ef696097ec22ba416f43554d4bff415e5645fbf1d822a6b13d718a5c5dec853f0b73ce3403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28f8b4a3d17041d88ff5837b2d4.pdf)

**Comment by gregrowles** [comment]
90% complete
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901eb60bbb258f4b83b6bc8c4ec2e03c21f5c6.png)
