### ISSUE TITLE
prevent multiple searches and multiple interactions

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#25]

**Comment by gregrowles** [comment]
blockButton.js > btnTag.hasClass( 'clicked' )

**Comment by gregrowles** [comment]
working on localhost, pls await merge + upload

**Comment by BRaimbault** [comment]
Back in v1.0.0.32

**Comment by BRaimbault** [comment]
Still happening in v1.0.0.33

**Comment by BRaimbault** [comment]
I also think we should prevent the user from clicking other buttons in other blocks, such as tabs, otherwise it creates wired situations.
