### ISSUE TITLE
hamburger icon update

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#28]
https://codepen.io/elijahmanor/pen/Igpoe

**Comment by gregrowles** [comment]
working on local Dev instance; uploaded to stableDev
![hamburgerIcon.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46e09597219791ae8afb9640ab53b2d86b56357c2301a03f32dfa17dbc122d585e5846fd48585845fdf9897da7e26e248d5402ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e48c8ea3c2de58e8c4b370c48.gif)
