### ISSUE TITLE
sync icon update

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#31]
Icon:
https://fontawesome.com/icons/sync?style=solid

Animate:
https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons

**Comment by gregrowles** [comment]
just realized we can 'spin' the icon opposite direction...
![spin_backwards.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46fb84932dbd81a88ce2a842b659e3d665043761260ea62864c7b96aea412b57565e49a410515f43fdf8892bf0b76822de5b03e4c3714d36976345f3e5db55ea43a82a994d84bcbd8f48c4ef3424e38b884b36191755.gif)
