### ISSUE TITLE
fav button - online/offline targets

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#38]

**Comment by gregrowles** [comment]
Solved, ready for testing
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901eb80bbb258f4b82bfb58d49c8e13c22f5c6.png)
