### ISSUE TITLE
Remove advanced login option

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#4]
We reached the conclusion that in the future we will manage access to different webservices via different urls, eg:
- https://apps.mis-psi.org/cws/ for production
- https://apps.mis-psi.org/cws-train/ for training
- https://apps.mis-psi.org/cws-dev/ for development

So we don't need advanced login options anymore.
We will simplify the login screen to keep only the simple login option.

![Screenshot_2018-12-06-14-20-57.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417753e7952ee7a24c8b178f2172c43434d0eee1e020a17b8eb8339a3e53c76835d0ce580645f73c73c11acee834bed55bd28825d99a4fedb1294b7607caddecd5d340c071883fe5831a4984bca5ff74be84850b65e.jpg)

**Comment by BRaimbault** [comment]
Check mobile layout

**Comment by BRaimbault** [comment]
Change text form "Simple options" to "Login"

**Comment by gregrowles** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901dbe0bbb258f4b87b1bd8348c6ef3f27f5c6.png)

done

**Comment by BRaimbault** [comment]
Good!

There the arrow to show/hide the block is behaving  strangely but there is no rush in fixing that. We will open a new task later.
