### ISSUE TITLE
new endpoints to capture follow-up

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#41]

**Comment by jturtler** [comment]
For 'Follow-up' Search, use "voucherStatus": "RDX" to get the already redeemed one.
For actual 'Follow-up' register, send 'activityNP' (with 'hiddenVal') set to 'FUP' to 'redeem' endpoint.   
It should perform 'Follow-up'.

For followUp, we currently designed for 'NP' case only.  Should we make the followup universal to other country as well?
