### ISSUE TITLE
review walk-in capture

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#44]

**Comment by jturtler** [comment]
Normal 'Walk-In' should be working.  <-- Find By detail search, then, do walk-in register.
Search by voucher code returning voucher not in issue status, and then, do 'Walk-In' needs some coding change.  (web service needs to return voucher/client data always, even in voucher 'notInIssueState' case)

**Comment by gregrowles** [comment]
Seems to work okay > PWA not generating a voucher code/number? what is best approach?

**Comment by BRaimbault** [comment]
Creating a new specific issue
