### ISSUE TITLE
Change app logo

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#5]
Please change the app logo to CwS logo.
Can we also add the text PWA to differentiate from the android app and a bug (animal) to highlight it is in development?

![Screenshot_2018-12-06-14-34-48.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417753e7952ee7a24c8b07cf2162343434d0eee1e020a17b8eb8339a3e53c76835d0ce580645f73c73c11acee834bed55bd28825d99a4fedb1294b7607caddecd5d340c041083fe5831a4984bcb5bf24ee94454b65e.jpg)

**Comment by gregrowles** [comment]
Done on my local Dev instance; should be available for testing very soon

**Comment by BRaimbault** [comment]
Looks good for now.

We will need to change background colour later (currently dark blue, see top bar in the screenshot below) .
![Screenshot_20181210-152440.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781476236455f67924d1b36af3006b1300051bff054a5556f9aa892dafb73b78db550bead06c5f74903c45feec8517b613a632c91edbe2e3d7158abd7f37ed998e48341f001c8dfb5837a09c48ca5af759ac.png)

**Comment by BRaimbault** [comment]
Ok background colour fixed!
