### ISSUE TITLE
translation via poEditor

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#50]
Step1: Research: possible performance improvments

Step2: Implementation

**Comment by BRaimbault** [comment]
Documentation:
https://poeditor.com/docs/api

**Comment by gregrowles** [comment]
James has developed a solution > to be implemented more tightly with existing forms

**Comment by gregrowles** [comment]
nearing complete; we may need a separate card/method to track missing (in js code) translatable texts
