### ISSUE TITLE
Ensure cache-clean/app-reset button always available

### ISSUE THREAD

**Issue by gregrowles** [psi-mis/connectPWA-pm#60]
When upgrading or logging into app (using DCD script that is not supported by latest version of appShell) > ensure the user has a way to refresh appShell as per Rodolofo's experience logging in with Honduras user account

**Comment by gregrowles** [comment]
Have added 'clean up' click event to CwS icon on landing page > to be given strict testing pls

**Comment by BRaimbault** [comment]
Testing: replicate Rodolfo's experience
