### ISSUE TITLE
sync all transaction > icons update

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#65]
After sync all process is triggered, upload status of transactions in listingPage

**Comment by gregrowles** [comment]
Will move redeemList (icon + info display) functions from blockList to FormUtil so they're accessible to both bulk-sync function + single-item sync click event

**Comment by gregrowles** [comment]
Bulk sync process now stepping through redeemList items - triggering icon rotate() and updating status + messages per item
