### ISSUE TITLE
[workbox] monitor user activity and devices

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#67]

**Comment by gregrowles** [comment]
a) link to #71 (googleAnalytics) for activity tracking; 
b) device info not possible, we are limited to what is currently supported through navigator object. Perhaps known screen-resolution may assist us pointing towards likely devices matching screen size - not an elegant or accurate determining method

**Comment by gregrowles** [comment]
let's close this - link #71
