### ISSUE TITLE
Login header clean up

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#7]
*[Version tested: 1.0.20]*

We dont need to see:
- The login text
- The service provision text
And we can replace these by the name of the app (at the moment it is Connect, but we'd like to replace it with a less generic name, if you have any creative idea...).

Also we don't need:
- The online / offline mode text the logo is enough
- Finally the refresh green arrows do not seem mandatory anymore if we have the update mechanism in place. In case it si still required, maybe we can hide it in the settings or about screen?

![Screenshot_2018-12-06-15-15-25.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417753e7952ee7a25c8b27df2102e43434d0eee1e020a17b8eb8339a3e53c76835d0ce580645f73c73c11acee834bed55bd28825d99a4fedb1294b7607caddecd5d340c041f83fe5831a4984bce58f74ee34c5cb65e.jpg)

**Comment by BRaimbault** [comment]
@BRaimbault  Ask designer for better offline / online icons

**Comment by BRaimbault** [comment]
![header.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46e0919b278791ebc3abaf51ab57f5973d047d317c07f37d29d4b470be1b2b565e5e4eac17590b16a8fe8122b4aa2e32db025fb28c341521842f1bbeb98515be04be248a4882b7b88f4cc7e12f68.jpg)

**Comment by gregrowles** [comment]
I've obtained great candidate SVG files, see screenshots below

**Comment by gregrowles** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901eb80bbb258f4b87b1be8844c2e9352df5c6.png)

**Comment by gregrowles** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f62820d3ba79e81a7a585f584fad41580945a8abdd2caebf2e6c981e5ab38532022d8c6853beb2901dbf0bbb258f4b87b1be894ac4e03923f5c6.png)

**Comment by gregrowles** [comment]
Application title above now read from manifest.json (short_name)

**Comment by BRaimbault** [comment]
*[Version tested: 1.0.21]*

Looks better! Thanks!

1 issue:

- App name does no show on my android device:
![Screenshot_20181210-152440.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781476236455f67924d1b36af3006b1300051bff054a5556f9aa892dafb73b78db550bead06c5f74903c45feec8517b613a632c91edbe2e3d7158abd7f37ed998d4f341f001c8dfb5834a99c4bcc58f159ac.png)

4 changes:

- Can we maintain app version?

- Also I suggest a small change to align better the app name text:
top: 10px > 5px (please use 5px not 4 as indicated in the capture)

![Screenshot_1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf51fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba821824584b3b88e48c4e13523e58f8e4f2c53.jpg)

- Can we update the online/offline icons?
See card #30
https://waffle.io/psi-mis/connectPWA-pm/cards/5c0e49963abed7009f921da7

- Can we update the .form-type-text class to width:99% ?
![Screenshot_2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf61fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba821824584b3b88e48c5e83a25e18c8e482c53.jpg)
