### ISSUE TITLE
support inputType: phone

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#78]
https://developer.android.com/training/keyboard-input/style.html

**Comment by gregrowles** [comment]
https://inputtypes.com >> type="tel" > displays numeric input keyboard; is this the keyboard layout you want (@Bruno)?
![Screenshot_20190227-095438.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd791475246454fa7e24d6bb6af3006b1300051bff054a5556f9aa892dafb73b78db550bead06c5f74903c45feec8517b613a632c91edbe2e3d7158abd7f37ed998e48341f001d88fd5831a19e4bcb5df659ac.jpg)
