### ISSUE TITLE
After logging, go to listing page

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#8]
After login, we want to go to the listing page, not to a form as in the current case.

https://drive.google.com/file/d/1R-Hz-l5ZJG2k-tpS7KKxJYMnjepbwzjR/view?usp=drivesdk

Is this configurable? (it does not need to be)

**Comment by gregrowles** [comment]
This is configurable; see example dcd@MZ (areas.online), find --> startArea: true
