### ISSUE TITLE
Translations / Display languages available dynamically

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#82]
I added a new languages to the list of languages in POEditor (French):
![Screenshot_1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf51fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b98849c1e93b2de78c874e2c53.jpg)

But it does not display in the list of available languages in the app:
![Screenshot_2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf61fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba821834584b3b98849c1e93b2ce18c8d4e2c53.jpg)

The app should be able to find language list dynamically from the configuration files (a given configuration is usually fully translated in English + one or two country language - but not in all available languages as form differ from country to country).

**Comment by BRaimbault** [comment]
Pending question to James

**Comment by gregrowles** [comment]
just tested in PWA > there is no automated check to see if new language translations are available; until a better solution is developer > user will have to click 'Language pack date' > 'update' button

**Comment by BRaimbault** [comment]
This is not to see if language pack has to be updated (Issue #84), this is to list available languages.
