### ISSUE TITLE
List header clean up

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#9]
*[Version tested: 1.0.20]*

- We don't need the app logo anymore from that point. We can replace it with the menu button.
- The menu button should be animated (three lines to cross).

Also we don't need:
- The service provision text
- The online / offline mode text the logo is enough, by the way, the cloud logo was meant to convey this online / offline idea, so we should use this one.
- Finally the refresh green arrows do not seem mandatory anymore if we have the update mechanism in place. In case it si still required, maybe we can hide it in the settings or about screen?

![Screenshot_2018-12-06-15-35-01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417753e7952ee7a25c8b07df2122a43434d0eee1e020a17b8eb8339a3e53c76835d0ce580645f73c73c11acee834bed55bd28825d99a4fedb1294b7607caddecd5d340c041f83fe5831a4984bcf58f549e84c50b65e.jpg)

**Comment by BRaimbault** [comment]
![header2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46e0919b278791fbcda5fd53b652fa912a5265296b51a07b26dcb27fe7432251585e4fac410e5e10aead8e23afa42062c80d55b98e30063e937f03a6aa8316b500bf248f4e82b1b88a4ec7eb3a37aa.jpg)

**Comment by gregrowles** [comment]
Done on local Dev instance
![newMenuLayout.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46e6918d0e878dbca3e8a64cb149b2d86b56357c2301a03f32dfa17dbc122d585e5846fd48585845fdf9897da7e26e248d5402ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98e48c4ea352de18f8d463a0c48.gif)

**Comment by BRaimbault** [comment]
*[Version tested: 1.0.21]*

Already looks much better!

- Can we make sure the styling is consistent with the login header for username text?
* top: 5px
* font-size: 18pt
* take out italic

![Screenshot_3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ad6bdd6d76bd0012828dfb/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf71fbcd6395428792c07b7692ac7b62bef14225058571fa5415f5e45fcf9df2af2e46877825519f1c32f0e2a92624cf5f2d75dad0ba821824584b3b88e48c5e93c2dee88894d2c53.jpg)

- Can we also update the menu icon?
See issue #28
https://waffle.io/psi-mis/connectPWA-pm/cards/5c0e43b816cb04009d622266
